# config.yaml

#Provide the path of your working directory. Example path is given below.
workdir: "/home/sutripa/Benchmarking/assembly_pipeline"
#Provide the path of the filtered long reads. Example path is given below  
filtered_long_reads: "/home/sutripa/Benchmarking/Inhouse_data/268/highQuality-reads.fastq"
#Mention number of threads to use
threads: 40
#Provide the path of the filtered paired end short reads. Example path is given below for R1 and R2
filtered_short_reads:
  R1: "/home/sutripa/Benchmarking/Inhouse_data/268/268I_R1.fastq"
  R2: "/home/sutripa/Benchmarking/Inhouse_data/268/268I_R2.fastq"
#Give the organism name from Busco database for genome quality assesment, Example organism is given below.    
busco_lineage: cyanobacteria_odb10
